# Generated by Django 2.0.3 on 2019-04-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_remove_studentuser_psw'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(upload_to='hotpic')),
                ('index', models.IntegerField(unique=True)),
            ],
        ),
    ]
